// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plmsnuoclmrbzgfjvssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbXNudW9jbG1yYnpnZmp2c3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyOTUzNjYsImV4cCI6MjA0Nzg3MTM2Nn0.vfRJcDOcEWWySglp8DZixsDJKqBmzpB-3cdV-CgRfUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);